version: 0.2

phases:
  install:
    commands:
      - echo "Installing..."

  build:
    commands:
      - cd registration-app
      - mvn clean package

artifacts:
  files:
    - registration-app/target/*.jar
