pipeline {
    agent any

    environment {
        DOCKER_CONFIG = '/home/ec2-user/.docker'
        PATH = "/usr/bin:/usr/local/bin:/usr/libexec/docker/cli-plugins:$PATH"
    }

    stages {

        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/Balachandru-ai/user-maven.git'
            }
        }

        stage('Show Files') {
            steps {
                sh '''
                pwd
                ls -la
                ls -la registration-app
                '''
            }
        }

        stage('Stop Old Containers') {
            steps {
                dir('registration-app') {
                    sh '''
                    /usr/bin/docker compose version
                    /usr/bin/docker compose down || true
                    '''
                }
            }
        }

        stage('Pull Latest Image') {
            steps {
                sh '''
                docker pull balachandru1/registration-app:latest
                '''
            }
        }

        stage('Start Containers') {
            steps {
                dir('registration-app') {
                    sh '''
                    /usr/bin/docker compose version
                    /usr/bin/docker compose up -d
                    '''
                }
            }
        }

        stage('Verify Running Containers') {
            steps {
                sh '''
                docker ps
                '''
            }
        }
    }

    post {
        success {
            echo '✅ Deployment completed successfully and pipeline is successfully created'
        }
        failure {
            echo '❌ Deployment failed and got error'
        }
    }
}
