pipeline {
    agent { label 'linux' }

    environment {
        DOCKER_CONFIG = '/home/ec2-user/.docker'
    }

    stages {
        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/Balachandru-ai/user-maven.git'
            }
        }

        stage('Show Files') {
            steps {
                sh '''
                pwd
                ls -la
                ls -la registration-app
                '''
            }
        }

        stage('Stop Old Containers') {
            steps {
                dir('registration-app') {
                    sh '''
                    pwd
                    ls -la
                    docker compose down || true
                    '''
                }
            }
        }

        stage('Build and Start Containers') {
            steps {
                dir('registration-app') {
                    sh '''
                    pwd
                    ls -la
                    docker compose up -d --build
                    '''
                }
            }
        }

        stage('Verify Running Containers') {
            steps {
                dir('registration-app') {
                    sh '''
                    docker ps
                    docker compose ps
                    '''
                }
            }
        }
    }

    post {
        success {
            echo 'Deployment completed successfully'
        }
        failure {
            echo 'Deployment failed'
        }
    }
}
